/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import Questions.MCQMA;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Dimitra
 */
public class MCQMAPanel_old extends javax.swing.JPanel {

    /**
     * Creates new form MCQMAPanel
     */
    public MCQMAPanel_old(JFrame frame){
        this(); 
        this.frame = frame; 
    }
    
        public MCQMAPanel_old() {
        initComponents();
        this.model = new DefaultListModel(); 
        this.AnswerList.setModel(this.model);
       // this.AnswerList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        this.indices = new ArrayList(); 
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        QuestionTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AnswerList = new javax.swing.JList<>();
        AddAnswer = new javax.swing.JButton();
        EditAnswer = new javax.swing.JButton();
        RemoveAnswer = new javax.swing.JButton();
        Ok = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Question");

        QuestionTextArea.setColumns(20);
        QuestionTextArea.setRows(5);
        jScrollPane1.setViewportView(QuestionTextArea);

        jLabel2.setText("Answers");

        AnswerList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnswerListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(AnswerList);

        AddAnswer.setText("Add Answer");
        AddAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAnswerActionPerformed(evt);
            }
        });

        EditAnswer.setText("Edit Answer");
        EditAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditAnswerActionPerformed(evt);
            }
        });

        RemoveAnswer.setText("Remove Question");

        Ok.setText("Ok");

        Cancel.setText("Cancel");

        Clear.setText("Clear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddAnswer)
                                .addGap(51, 51, 51)
                                .addComponent(EditAnswer))
                            .addComponent(RemoveAnswer)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ok)
                                .addGap(18, 18, 18)
                                .addComponent(Cancel)
                                .addGap(18, 18, 18)
                                .addComponent(Clear)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddAnswer)
                    .addComponent(EditAnswer))
                .addGap(18, 18, 18)
                .addComponent(RemoveAnswer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ok)
                    .addComponent(Cancel)
                    .addComponent(Clear))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAnswerActionPerformed
        String answer = JOptionPane.showInputDialog("Enter an answer"); 
        ((DefaultListModel)this.AnswerList.getModel()).addElement(answer);
    
    }//GEN-LAST:event_AddAnswerActionPerformed

    private void EditAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditAnswerActionPerformed
        int index = AnswerList.getSelectedIndex();
      if(index != -1){
          String answer = JOptionPane.showInputDialog("Enter an answer"); 

          ((DefaultListModel)this.AnswerList.getModel()).remove(index);
        ((DefaultListModel)this.AnswerList.getModel()).add(index, answer);          
      }
        
    }//GEN-LAST:event_EditAnswerActionPerformed

    private void AnswerListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnswerListMouseClicked
        System.out.println("The list is clicked! ");
        int A[] = this.AnswerList.getSelectedIndices();
        System.out.println(Arrays.toString(A));
        
    }//GEN-LAST:event_AnswerListMouseClicked
    private void RemoveAnswerActionPerformed(java.awt.event.ActionEvent evt) {                                             
      //  ((DefaultListModel)this.jList1.getModel()).
      int index = AnswerList.getSelectedIndex();
      if(index != -1){
          ((DefaultListModel)this.AnswerList.getModel()).remove(index); 
      }
    }                                            
                                      

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {                                   
        String statement = this.QuestionTextArea.getText();
        ArrayList<String> answers = new ArrayList(); 
        int capacity = ((DefaultListModel)this.AnswerList.getModel()).getSize();
        for(int i=0;i<capacity;i++){
            answers.add((String)((DefaultListModel)this.AnswerList.getModel()).getElementAt(i));
        }
        this.question = new MCQMA(statement, answers, null ); 
        System.out.println(this.question);
        ((MakeMCQMAQuestion)this.frame).setQ(this.question); 
                 
    }                                  

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {                                      
        this.QuestionTextArea.setText(""); 
        ((DefaultListModel)this.AnswerList.getModel()).removeAllElements();
        this.jLabel3.setText("");
         
    }                                     

    MCQMA question; 
    ArrayList<Integer> indices; 
    DefaultListModel model; 
    JFrame frame; 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAnswer;
    private javax.swing.JList<String> AnswerList;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Clear;
    private javax.swing.JButton EditAnswer;
    private javax.swing.JButton Ok;
    private javax.swing.JTextArea QuestionTextArea;
    private javax.swing.JButton RemoveAnswer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
