/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import Questions.MCQWSA;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dimitra
 */
public class MCQWSAPanel extends javax.swing.JPanel {

    public MCQWSAPanel(JFrame frame){
        this(); 
        this.frame = frame; 
        
    }
    public MCQWSAPanel() {
        initComponents();
        this.model = new DefaultListModel(); 
        this.AnswerList.setModel(this.model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        QuestionTextArea = new javax.swing.JTextArea();
        Ok = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AnswerList = new javax.swing.JList<>();
        AddAnswer = new javax.swing.JButton();
        RemoveAnswer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EditAnswer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        QuestionTextArea.setColumns(20);
        QuestionTextArea.setRows(5);
        jScrollPane1.setViewportView(QuestionTextArea);

        Ok.setText("Ok");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        AnswerList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnswerListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(AnswerList);

        AddAnswer.setText("Add Answer");
        AddAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAnswerActionPerformed(evt);
            }
        });

        RemoveAnswer.setText("Remove Answer");
        RemoveAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveAnswerActionPerformed(evt);
            }
        });

        jLabel1.setText("Question");

        jLabel2.setText("Answers");

        EditAnswer.setText("Edit Answer");
        EditAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditAnswerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ok)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cancel)
                                .addGap(43, 43, 43)
                                .addComponent(Clear))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(AddAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(EditAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(RemoveAnswer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditAnswer)
                    .addComponent(AddAnswer))
                .addGap(18, 18, 18)
                .addComponent(RemoveAnswer)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ok)
                    .addComponent(Cancel)
                    .addComponent(Clear))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAnswerActionPerformed
       
        String answer = JOptionPane.showInputDialog("Enter an answer"); 
        if(answer.isEmpty()){return;}

    /*    int response = JOptionPane.showConfirmDialog(null, "Do you want to continue?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    if (response == JOptionPane.NO_OPTION) {
    
    } else if (response == JOptionPane.YES_OPTION) {
      System.out.println("Yes button clicked");
    } else if (response == JOptionPane.CLOSED_OPTION) {
      System.out.println("JOptionPane closed");
    }
*/
      ((DefaultListModel)this.AnswerList.getModel()).addElement(answer);
    }//GEN-LAST:event_AddAnswerActionPerformed

    private void RemoveAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveAnswerActionPerformed
      //  ((DefaultListModel)this.jList1.getModel()).
      int index = AnswerList.getSelectedIndex();
      if(index != -1){
          ((DefaultListModel)this.AnswerList.getModel()).remove(index); 
      }
    }//GEN-LAST:event_RemoveAnswerActionPerformed

    private void EditAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditAnswerActionPerformed
         int index = AnswerList.getSelectedIndex();
      if(index != -1){
          String answer = JOptionPane.showInputDialog("Enter an answer"); 

          ((DefaultListModel)this.AnswerList.getModel()).remove(index);
        ((DefaultListModel)this.AnswerList.getModel()).add(index, answer);          
      }
          
    }//GEN-LAST:event_EditAnswerActionPerformed

    private void AnswerListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnswerListMouseClicked
        // this runs when I click an answer.
        int index = this.AnswerList.getSelectedIndex();
        this.correctIndex = index; 
        this.jLabel3.setText("Correct #:"+this.correctIndex);
    }//GEN-LAST:event_AnswerListMouseClicked

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        String statement = this.QuestionTextArea.getText();
        ArrayList<String> answers = new ArrayList(); 
        int capacity = ((DefaultListModel)this.AnswerList.getModel()).getSize();
        for(int i=0;i<capacity;i++){
            answers.add((String)((DefaultListModel)this.AnswerList.getModel()).getElementAt(i));
        }
        this.question = new MCQWSA(statement, answers, this.correctIndex); 
        System.out.println(this.question);
        ((MakeMCQWSAQuestion)this.frame).setQ(this.question); 
                 
    }//GEN-LAST:event_OkActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        this.QuestionTextArea.setText(""); 
        ((DefaultListModel)this.AnswerList.getModel()).removeAllElements();
        this.correctIndex = -1; 
        this.jLabel3.setText("");
         
    }//GEN-LAST:event_ClearActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
         this.frame.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    MCQWSA question; 
    int correctIndex = -1; 
    DefaultListModel model; 
    JFrame frame; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAnswer;
    private javax.swing.JList<String> AnswerList;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Clear;
    private javax.swing.JButton EditAnswer;
    private javax.swing.JButton Ok;
    private javax.swing.JTextArea QuestionTextArea;
    private javax.swing.JButton RemoveAnswer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
